max_electrolyzer_capacity: 0
max_wind_capacity: 10
hydrogen_price: 6
min_daily_hydrogen_production: 0.0
CVaR_type: deviation
alpha: 0.9
price_quantile: false
linear_features:
- intercept
- lambda_DA_RE
- energy_FC
- DK1_Accepted_Down_Volume_(MW)
- DK1_Accepted_Up_Volume_(MW)
- DK2_Accepted_Down_Volume_(MW)
- DK2_Accepted_Up_Volume_(MW)
- Solar_FC
- Solar_FC_error_hourly_rollavg
- Wind_offshore_FC
- Wind_offshore_FC_error_hourly_rollavg
- Wind_onshore_FC
- Wind_onshore_FC_error_hourly_rollavg
- abs_diff_markets_RE_hourly_rollavg
- diff_markets_RE_hourly_rollavg
- lambda_DA_FC_normalized
- lambda_DA_RE_hourly_rollavg
- lambda_IM_hourly_rollavg
- load_FC
- load_FC_error_hourly_rollavg
- missing_capacity_RE_hourly_rollavg
non_linear_features:
- intercept
- lambda_DA_RE
- energy_FC
- DK1_Accepted_Down_Volume_(MW)
- DK1_Accepted_Up_Volume_(MW)
- DK2_Accepted_Down_Volume_(MW)
- DK2_Accepted_Up_Volume_(MW)
- Solar_FC
- Solar_FC_error_hourly_rollavg
- Wind_offshore_FC
- Wind_offshore_FC_error_hourly_rollavg
- Wind_onshore_FC
- Wind_onshore_FC_error_hourly_rollavg
- abs_diff_markets_RE_hourly_rollavg
- diff_markets_RE_hourly_rollavg
- lambda_DA_FC_normalized
- lambda_DA_RE_hourly_rollavg
- lambda_IM_hourly_rollavg
- load_FC
- load_FC_error_hourly_rollavg
- missing_capacity_RE_hourly_rollavg
- lambda_DA_FC_zeta_1.0_mu_-0.37961439398567787
- lambda_DA_FC_zeta_1.0_mu_0.02682140396829682
- lambda_DA_FC_zeta_1.0_mu_0.3542880027276621
- energy_FC_zeta_0.3550017391908838_mu_0.11874412244809437
- energy_FC_zeta_0.3550017391908838_mu_0.39136321503461935
- energy_FC_zeta_0.3550017391908838_mu_0.8015558154203456
kernel_features:
- lambda_DA_RE
- energy_FC
- DK1_Accepted_Down_Volume_(MW)
- DK1_Accepted_Up_Volume_(MW)
- DK2_Accepted_Down_Volume_(MW)
- DK2_Accepted_Up_Volume_(MW)
- Solar_FC
- Solar_FC_error_hourly_rollavg
- Wind_offshore_FC
- Wind_offshore_FC_error_hourly_rollavg
- Wind_onshore_FC
- Wind_onshore_FC_error_hourly_rollavg
- abs_diff_markets_RE_hourly_rollavg
- diff_markets_RE_hourly_rollavg
- lambda_DA_FC_normalized
- lambda_DA_RE_hourly_rollavg
- lambda_IM_hourly_rollavg
- load_FC
- load_FC_error_hourly_rollavg
- missing_capacity_RE_hourly_rollavg
eta_storage: 0.88
p_min: 0.01
n_segments: 2
cold_start_cost: 1
p_standby: 0.01
P_eta_max: 0.28274916323188165
eta_max: 19.7793257953947
p_val:
- 1.0000000000000002e-06
- 2.8274916323188165e-05
- 0.0001
Area: 0.009948163051108466
eta_full_load: 17.54697396557492
N_p: 3
N_s: 2
a:
- 20.474274478410113
- 16.666953225878288
b:
- -1.9649615861170398e-05
- 8.800207396966204e-05
Q_0: 0
Q_1: 0
T_op: 90
Pr: 30
kernel_gamma: 3
kernel_degree: 2
window_setup: rolling_window
train_length: 15
val_length: 2
test_length: 1
rbf_kernel_alpha_array:
- 0.0
poly_kernel_alpha_array:
- 0.0
beta_array:
- 0.0
- 0.1
- 0.5
- 1.0
- 5.0
- 10.0
- 20.0
CVaR_array:
- 0.0
- 0.5
- 1.0
- 2.0
- 5.0
- 10.0
